sudo: false
language: node_js
  - "4.3"

install:
  - npm install -g elm
  - elm-package install -y

before_script:
    - cd tests
    - elm-make Test.elm --yes --output test.js

script: node test.js
